### ISSUE TITLE
What is the point of the constants like CONSUMER_KEY

### ISSUE THREAD

**Issue by mudrd8mz** [iamandrew/moodle-block_twitter#3]
In locallib.php, constants CONSUMER_KEY, CONSUMER_SECRET, TWITTER_TOKEN and TWITTER_TOKEN_SECRET are defined. If nothing else then they violate the prefix naming rules https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

More importantly, I really do not see their point here as they are only used couple of lines below as parameters for the `TwitterOAuth` constructor.

**Comment by iamandrew** [comment]
Agreed, and constants removed
