### ISSUE TITLE
The tweet text does not seem to be sanitized

### ISSUE THREAD

**Issue by mudrd8mz** [iamandrew/moodle-block_twitter#6]
If I am not wrong, you are directly outputting the tweet text into the HTML without `s()` or `format_text()`. I have not studied the details of the twitter API but it might be potentially dangerous and allow XSS via the malicious tweet text.

Related to this, why do you have RISK_XSS listed in db/access.php? It does not seem right to me to have that flag for `block/twitter:addinstance` and not for `block/twitter:myaddinstance`. I believe that you must make it not vulnerable to XSS as even the editing teacher does not really provide the displayed contents here.

**Comment by iamandrew** [comment]
Tweet text will now be sanitised, and RISK_XSS removed for both caps
